### ISSUE TITLE
Not able to see the thread group

### ISSUE THREAD

**Issue by thejusdutt** [JoseLuisSR/awsmeter#18]
I installed the plugin, but I am not getting thread groups related sqs or sns

Java version - 11
Jmeter versionn - 5.5

**Comment by anmols28** [comment]
it resolved after upgrading to java version 17

**Comment by JoseLuisSR** [comment]
Hi @thejusdutt 

Could you please try to use awsmeter with Java 17 and check again?

You can use gradlew wrapper to build uberJar with the command

`gradlew uberJar`

The version of gradle wrapper of it project is 7.5.1

Or you can use the gradle in your workspace, make sure its version isequal or above 7.3
