### ISSUE TITLE
awsmeter is not used aws_session_token from .aws\credentials

### ISSUE THREAD

**Issue by drsprt** [JoseLuisSR/awsmeter#2]
I have MFA credentials:
`[default]`
`aws_access_key_id = AKxxxxxxxxxxxxxxxxT4`
`aws_secret_access_key = wt36xxxxxxxxxxxxxxxxxxxxxxxx26KO`
`[mfa]`
`aws_access_key_id = ASxxxxxxxxxxxxxxxxR24`
`aws_secret_access_key = DvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhW`
`aws_session_token = FwoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSK+LTq`

and set parameter of 'org.apache.jmeter.protocol.aws.sqs.SQSProducerStandardQueue' Java Request sampler:
`aws_configure_profile = mfa`

In this case Response Body is "The security token included in the request is invalid."
Does **awsmeter** not read **aws_session_token** from file?

**awsmeter** is working only if following parameter of Java Request sampler is define:
`aws_session_token = FwoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSK+LTq`

**Comment by JoseLuisSR** [comment]
Hi @drsprt

Sorry for the delay in my response.

The new feature to get the session token from the credentials file is ready.
I have created the tag v2.1.1 with the new version of awsmeter, it is ready to use.

Thank you report it.
