### ISSUE TITLE
Cannot call GetSessionToken with session credentials. 

### ISSUE THREAD

**Issue by xander1234** [JoseLuisSR/awsmeter#5]
When I use the SNS producer Standar and FIFO always I get the error Cannot call GetSessionToken with session credentials.

**Comment by JoseLuisSR** [comment]
Hi @xander1234 

Sorry for the delay in my response.

I fix it with the PR #9 
I have created the tag v2.1.1 with the new version of awsversion, it is ready to use.

Thank you to report it.
